#
# Configuration for NationsRPG Core Plugin
#
# Authored by byteful#0001 for v${version}
#

# Should the core launch in beta mode?
beta: true

# Settings for MySQL connection.
mysql:
  host: "localhost"
  port: 3306
  user: "root"
  pass: "password"
  database: "NationsRPG"

# The class for the map that should be used for spawn. Has to be implemented by com.nationsrpg.plugin.core.api.map.SpawnMap.
map: "com.nationsrpg.plugin.core.maps.ClassicSpawnMap"